name = "raffle-arcade-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[d1_databases]]
binding = "DB"
database_name = "raffle-arcade"
database_id = "YOUR_DATABASE_ID"

[[kv_namespaces]]
binding = "CACHE"
id = "YOUR_KV_NAMESPACE_ID"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "raffle-arcade-assets"

[[durable_objects.bindings]]
name = "RAFFLE_DO"
class_name = "RaffleDO"
script_name = "raffle-arcade-api"

[[migrations]]
tag = "v1"
new_classes = ["RaffleDO"]

[secrets]
# Add these in Cloudflare dashboard:
# ADMIN_SECRET
# SERVER_SEED