name = "raffle-arcade-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
vars = { ENVIRONMENT = "production" }

[[d1_databases]]
binding = "DB"
database_name = "raffle-arcade"
database_id = "ed07c670-2cf3-4aa4-a3f5-74ccba4e30c9"

[[kv_namespaces]]
binding = "CACHE"
id = "2995cb5762b4480982d6d1ce2c881dac"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "raffle-arcade-assets"

[[durable_objects.bindings]]
name = "RAFFLE_DO"
class_name = "RaffleDO"
script_name = "raffle-arcade-api"

[[migrations]]
tag = "v1"
new_classes = ["RaffleDO"]

# Secrets to add in Cloudflare dashboard:
# ADMIN_SECRET
# SERVER_SEED
# DEV_WALLET_PRIVATE_KEY
# PAIR_TOKEN_MINT